# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/FocusAndNoFocus/namespace.coffee

module.exports = (require '../namespace').addNamespace('FocusAndNoFocus', class FocusAndNoFocus extends Neptune.PackageNamespace)
