// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/FocusAndNoFocus/namespace.js

module.exports = require('../namespace').addNamespace(
  'FocusAndNoFocus',
  class FocusAndNoFocus extends Neptune.PackageNamespace {}
);
