# generated by Neptune Namespaces
# file: art/react/demos/color_picker/index.coffee

module.exports =
ColorPicker            = require './namespace'
ColorPicker.Main       = require './main'
ColorPicker.Components = require './components'
ColorPicker.Models     = require './models'
ColorPicker.finishLoad(
  ["Main"]
)