# generated by Neptune Namespaces v0.4.1
# file: art/react/demos/color_picker/index.coffee

(module.exports = require './namespace')
.addModules
  Main: require './main'
require './components'
require './models'