# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/color_picker/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ColorPicker ||
Demos.addNamespace 'ColorPicker', class ColorPicker extends Neptune.Base
  ;