# generated by Neptune Namespaces
# file: art/react/demos/color_picker/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ColorPicker ||
Demos.addNamespace class ColorPicker extends Neptune.Base
  ;