// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Style/namespace.js

module.exports = require('../namespace').addNamespace(
  'Style',
  class Style extends Neptune.PackageNamespace {}
);
