# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Style/namespace.coffee

module.exports = (require '../namespace').addNamespace('Style', class Style extends Neptune.PackageNamespace)
