// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Chat/index.js

(module.exports = require('./namespace'))

.addModules({
  ChatMessage: require('./ChatMessage'),
  ChatModel:   require('./ChatModel'),
  ChatView:    require('./ChatView'),
  Main:        require('./Main'),
  StyleProps:  require('./StyleProps')
});