// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Chat/namespace.js

module.exports = require('../namespace').addNamespace(
  'Chat',
  class Chat extends Neptune.PackageNamespace {}
);
