# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Chat/namespace.coffee

module.exports = (require '../namespace').addNamespace('Chat', class Chat extends Neptune.PackageNamespace)
