# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Layout/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Layout ||
Demos.addNamespace 'Layout', class Layout extends Neptune.Base
  ;
