# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/Layout/namespace.coffee

module.exports = (require '../namespace').addNamespace('Layout', class Layout extends Neptune.PackageNamespace)
