# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/Chat/index.coffee

module.exports = require './namespace'
.addModules
  ChatMessage: require './ChatMessage'
  ChatModel:   require './ChatModel'  
  ChatView:    require './ChatView'   
  Main:        require './Main'       
  StyleProps:  require './StyleProps' 