# generated by Neptune Namespaces
# file: art/react/demos/color_picker/models/index.coffee

module.exports =
Models              = require './namespace'
Models.CurrentColor = require './current_color'
Models.finishLoad(
  ["CurrentColor"]
)