# generated by Neptune Namespaces v0.1.0
# file: art/react/demos/color_picker/models/namespace.coffee

ColorPicker = require '../namespace'
module.exports = ColorPicker.Models ||
ColorPicker.addNamespace class Models extends Neptune.Base
  ;