# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/color_picker/models/namespace.coffee

ColorPicker = require '../namespace'
module.exports = ColorPicker.Models ||
ColorPicker.addNamespace 'Models', class Models extends Neptune.Base
  ;