# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/Clock/index.coffee

module.exports = require './namespace'
.addModules
  CurrentTime: require './CurrentTime'
  Main:        require './Main'       