# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Clock/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CurrentTime: require './CurrentTime'
  Main:        require './Main'       