# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/Clock/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Clock ||
Demos.addNamespace 'Clock', class Clock extends Neptune.Base
  ;