# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/FluxChallenge/Data/namespace.coffee

module.exports = (require '../namespace').addNamespace('Data', class Data extends Neptune.PackageNamespace)
