# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/ColorPicker/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CurrentColor: require './CurrentColor'