// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Physics/namespace.js

module.exports = require('../namespace').addNamespace(
  'Physics',
  class Physics extends Neptune.PackageNamespace {}
);
