# generated by Neptune Namespaces v0.6
# file: art/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Art ||
Neptune.addNamespace 'Art', class Art extends Neptune.Base
  ;