# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/ScrollingDynamic/index.coffee

module.exports = require './namespace'
.addModules
  DynamicScroller: require './DynamicScroller'
  Main:            require './Main'           
  StyleProps:      require './StyleProps'     