# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ScrollingDynamic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ScrollingDynamic ||
Demos.addNamespace 'ScrollingDynamic', class ScrollingDynamic extends Neptune.Base
  ;
