# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/FluxChallenge/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'
require './Data'
require './Models'