# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/FluxChallenge/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.FluxChallenge ||
Demos.addNamespace 'FluxChallenge', class FluxChallenge extends Neptune.Base
  ;
require './Components/namespace';
require './Data/namespace';
require './Models/namespace'