# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DemoPalette:    require './DemoPalette'   
  DemoTextStyles: require './DemoTextStyles'
  StandardImport: require './StandardImport'
require './Animations'
require './Basic'
require './CandyStripe'
require './Chat'
require './Clock'
require './ColorExtractor'
require './ColorPicker'
require './ColorPicker2'
require './FluxChallenge'
require './Form'
require './Layout'
require './Physics'
require './Quixx'
require './ScrollingDynamic'
require './ScrollingInfinite'
require './Style'
require './Todos'
require './VoidProps'