# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/namespace.coffee

module.exports = (require '../namespace').addNamespace('Demos', class Demos extends Neptune.PackageNamespace)
require './Animations/namespace';
require './Basic/namespace';
require './CandyStripe/namespace';
require './Chat/namespace';
require './Clock/namespace';
require './ColorExtractor/namespace';
require './ColorPicker/namespace';
require './ColorPicker2/namespace';
require './FluxChallenge/namespace';
require './Form/namespace';
require './Layout/namespace';
require './Physics/namespace';
require './Quixx/namespace';
require './ScrollingDynamic/namespace';
require './ScrollingInfinite/namespace';
require './Style/namespace';
require './Todos/namespace';
require './VoidProps/namespace'