# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/namespace.coffee

Suite = require '../namespace'
module.exports = Suite.Demos ||
Suite.addNamespace 'Demos', class Demos extends Neptune.Base
  ;