# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/Physics/namespace.coffee

module.exports = (require '../namespace').addNamespace('Physics', class Physics extends Neptune.PackageNamespace)
