# generated by Neptune Namespaces
# this file: src/art/react/index.coffee

module.exports =
React        = require './namespace'
React.Demos  = require './demos'
React.Loader = require './loader'
React.finishLoad(
  ["Loader"]
)