# generated by Neptune Namespaces
# file: art/react/namespace.coffee

Art = require '../namespace'
module.exports = Art.React ||
class Art.React extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.React"

Art.addNamespace Art.React