# generated by Neptune Namespaces v0.1.0
# file: art/react/demos/clock/index.coffee

(module.exports = require './namespace')
.addModules
  CurrentTime: require './current_time'
  Main:        require './main'