# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/clock/index.coffee

module.exports = require './namespace'
.addModules
  CurrentTime: require './current_time'
  Main:        require './main'        