# generated by Neptune Namespaces
# file: art/react/demos/clock/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Clock ||
Demos.addNamespace class Clock extends Neptune.Base
  ;