# generated by Neptune Namespaces
# file: art/react/demos/clock/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Clock ||
class Demos.Clock extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.React.Demos.Clock"

Demos.addNamespace Demos.Clock