# generated by Neptune Namespaces v0.3.0
# file: art/react/demos/clock/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Clock ||
Demos.addNamespace 'Clock', class Clock extends Neptune.Base
  ;