# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Todos/namespace.coffee

module.exports = (require '../namespace').addNamespace('Todos', class Todos extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'