// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Todos/namespace.js

module.exports = require('../namespace').addNamespace(
  'Todos',
  class Todos extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Models/namespace');