// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/VoidProps/namespace.js

module.exports = require('../namespace').addNamespace(
  'VoidProps',
  class VoidProps extends Neptune.PackageNamespace {}
);
