# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Layout/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BasicLayoutDemo:     require './BasicLayoutDemo'    
  Button:              require './Button'             
  ChildrenLayoutDemo:  require './ChildrenLayoutDemo' 
  LayoutDemoContainer: require './LayoutDemoContainer'
  Main:                require './Main'               