// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Layout/index.js

(module.exports = require('./namespace'))

.addModules({
  BasicLayoutDemo:     require('./BasicLayoutDemo'),
  Button:              require('./Button'),
  ChildrenLayoutDemo:  require('./ChildrenLayoutDemo'),
  LayoutDemoContainer: require('./LayoutDemoContainer'),
  Main:                require('./Main')
});