// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/TicTacToe/namespace.js

module.exports = require('../namespace').addNamespace(
  'TicTacToe',
  class TicTacToe extends Neptune.PackageNamespace {}
);
