# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/TicTacToe/namespace.coffee

module.exports = (require '../namespace').addNamespace('TicTacToe', class TicTacToe extends Neptune.PackageNamespace)
