# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Basic copy/namespace.coffee

module.exports = (require '../namespace').addNamespace('BasicCopy', class BasicCopy extends Neptune.PackageNamespace)
