# generated by Neptune Namespaces v0.6
# file: art/react/demos/Chat/index.coffee

module.exports = require './namespace'
.addModules
  ChatMessage: require './chat_message'
  ChatModel:   require './chat_model'  
  ChatView:    require './chat_view'   
  Main:        require './main'        
  StyleProps:  require './style_props' 