# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/Chat/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Chat ||
Demos.addNamespace 'Chat', class Chat extends Neptune.Base
  ;