# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Multitouch/namespace.coffee

module.exports = (require '../namespace').addNamespace('Multitouch', class Multitouch extends Neptune.PackageNamespace)
