// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Multitouch/namespace.js

module.exports = require('../namespace').addNamespace(
  'Multitouch',
  class Multitouch extends Neptune.PackageNamespace {}
);
