// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Quixx/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:       require('./Main'),
  StyleProps: require('./StyleProps')
});
require('./Components');
require('./Models');