// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Quixx/namespace.js

module.exports = require('../namespace').addNamespace(
  'Quixx',
  class Quixx extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Models/namespace');