// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/CanvasPathFile/index.js

(module.exports = require('./namespace'))

.addModules({
  ClassPathPreview: require('./ClassPathPreview'),
  ExampleSvg:       require('./ExampleSvg'),
  Main:             require('./Main')
});