# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/CanvasPathFile/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ClassPathPreview: require './ClassPathPreview'
  ExampleSvg:       require './ExampleSvg'      
  Main:             require './Main'            