// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/CanvasPathFile/namespace.js

module.exports = require('../namespace').addNamespace(
  'CanvasPathFile',
  class CanvasPathFile extends Neptune.PackageNamespace {}
);
