# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/MotivationalPoster/Data/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Styles: require './Styles'