# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Quixx/Components/namespace.coffee

Quixx = require '../namespace'
module.exports = Quixx.Components ||
Quixx.addNamespace 'Components', class Components extends Neptune.Base
  ;
