# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/TextLayout/namespace.coffee

module.exports = (require '../namespace').addNamespace('TextLayout', class TextLayout extends Neptune.PackageNamespace)
