// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/TextLayout/namespace.js

module.exports = require('../namespace').addNamespace(
  'TextLayout',
  class TextLayout extends Neptune.PackageNamespace {}
);
