# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/FluxChallenge/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DarkJedi:  require './DarkJedi' 
  ObiWan:    require './ObiWan'   
  Paginator: require './Paginator'