# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/FluxChallenge/Models/namespace.coffee

module.exports = (require '../namespace').addNamespace('Models', class Models extends Neptune.PackageNamespace)
