// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/DrumMachine/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  DrumMachine: require('./DrumMachine'),
  DrumState:   require('./DrumState')
});