# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/DrumMachine/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DrumMachine: require './DrumMachine'
  DrumState:   require './DrumState'  