// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/WrapperComponents/namespace.js

module.exports = require('../namespace').addNamespace(
  'WrapperComponents',
  class WrapperComponents extends Neptune.PackageNamespace {}
);
