# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/WrapperComponents/namespace.coffee

module.exports = (require '../namespace').addNamespace('WrapperComponents', class WrapperComponents extends Neptune.PackageNamespace)
