# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Basic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Basic ||
Demos.addNamespace 'Basic', class Basic extends Neptune.Base
  ;
