# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/ColorExtractor/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ColorExtractor ||
Demos.addNamespace 'ColorExtractor', class ColorExtractor extends Neptune.Base
  ;