# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/CandyStripe/namespace.coffee

module.exports = (require '../namespace').addNamespace('CandyStripe', class CandyStripe extends Neptune.PackageNamespace)
