# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DemoPalette:    require './DemoPalette'   
  DemoTextStyles: require './DemoTextStyles'
  Loader:         require './Loader'        
  Main:           require './Main'          
  StandardImport: require './StandardImport'
require './Demos'