// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/index.js

(module.exports = require('./namespace'))

.addModules({
  Button:         require('./Button'),
  DemoPalette:    require('./DemoPalette'),
  DemoTextStyles: require('./DemoTextStyles'),
  Loader:         require('./Loader'),
  Main:           require('./Main'),
  StandardImport: require('./StandardImport')
});
require('./Demos');