# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.SuiteDemos', class SuiteDemos extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Demos/namespace'