// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.SuiteDemos',
  (class SuiteDemos extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Demos/namespace');