# generated by Neptune Namespaces v0.4.1
# file: art/react/demos/void_props/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.VoidProps ||
Demos.addNamespace 'VoidProps', class VoidProps extends Neptune.Base
  ;