# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/BasicHotLoading/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.BasicHotLoading ||
Demos.addNamespace 'BasicHotLoading', class BasicHotLoading extends Neptune.Base
  ;