// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Gestures/namespace.js

module.exports = require('../namespace').addNamespace(
  'Gestures',
  class Gestures extends Neptune.PackageNamespace {}
);
