# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Gestures/namespace.coffee

module.exports = (require '../namespace').addNamespace('Gestures', class Gestures extends Neptune.PackageNamespace)
