# generated by Neptune Namespaces v0.6
# file: art/react/demos/Animations/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Animations ||
Demos.addNamespace 'Animations', class Animations extends Neptune.Base
  ;