# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ColorPicker2/namespace.coffee

module.exports = (require '../namespace').addNamespace('ColorPicker2', class ColorPicker2 extends Neptune.PackageNamespace)
require './Components/namespace'