// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorPicker2/namespace.js

module.exports = require('../namespace').addNamespace(
  'ColorPicker2',
  class ColorPicker2 extends Neptune.PackageNamespace {}
);
require('./Components/namespace');