// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Animations/namespace.js

module.exports = require('../namespace').addNamespace(
  'Animations',
  class Animations extends Neptune.PackageNamespace {}
);
