// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorPicker2/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  ColorPicker2: require('./ColorPicker2'),
  ColorPicker3: require('./ColorPicker3')
});