# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ColorPicker2/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ColorPicker2: require './ColorPicker2'