# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Form/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Form ||
Demos.addNamespace 'Form', class Form extends Neptune.Base
  ;
