# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Textarea/namespace.coffee

module.exports = (require '../namespace').addNamespace('Textarea', class Textarea extends Neptune.PackageNamespace)
