// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Textarea/namespace.js

module.exports = require('../namespace').addNamespace(
  'Textarea',
  class Textarea extends Neptune.PackageNamespace {}
);
