# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/ColorPicker2/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main: require './Main'
require './Components'