# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/FluxChallenge/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:            require './App'           
  Button:         require './Button'        
  PlanetMonitor:  require './PlanetMonitor' 
  Slot:           require './Slot'          
  StandardImport: require './StandardImport'