# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/FluxChallenge/Components/namespace.coffee

FluxChallenge = require '../namespace'
module.exports = FluxChallenge.Components ||
FluxChallenge.addNamespace 'Components', class Components extends Neptune.Base
  ;
