// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorPicker/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  ColorPicker:   require('./ColorPicker'),
  ColorPicker1D: require('./ColorPicker1D'),
  ColorPreview:  require('./ColorPreview')
});