# generated by Neptune Namespaces v0.4.1
# file: art/react/demos/index.coffee

(module.exports = require './namespace')
require './basic'
require './buttons'
require './clock'
require './color_picker'
require './hot_basic'
require './paging_scroll_element'
require './physics'
require './quixx'