# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/namespace.coffee

React = require '../namespace'
module.exports = React.Demos ||
React.addNamespace 'Demos', class Demos extends Neptune.Base
  ;