# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/ScrollingInfinite/index.coffee

module.exports = require './namespace'
.addModules
  ColorScroller: require './ColorScroller'
  Main:          require './Main'         