# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/ScrollingInfinite/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScrollingInfinite', class ScrollingInfinite extends Neptune.PackageNamespace)
