# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ScrollingInfinite/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ScrollingInfinite ||
Demos.addNamespace 'ScrollingInfinite', class ScrollingInfinite extends Neptune.Base
  ;
