# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/VoidProps/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.VoidProps ||
Demos.addNamespace 'VoidProps', class VoidProps extends Neptune.Base
  ;