# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Todos/Components/namespace.coffee

Todos = require '../namespace'
module.exports = Todos.Components ||
Todos.addNamespace 'Components', class Components extends Neptune.Base
  ;
