# generated by Neptune Namespaces v0.6
# file: art/react/demos/ScrollingDynamic/index.coffee

module.exports = require './namespace'
.addModules
  DynamicScroller: require './DynamicScroller'
  Main:            require './main'           
  StyleProps:      require './StyleProps'     