# generated by Neptune Namespaces v0.6
# file: art/react/demos/ScrollingDynamic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ScrollingDynamic ||
Demos.addNamespace 'ScrollingDynamic', class ScrollingDynamic extends Neptune.Base
  ;