// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/FluxChallenge/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  DarkJedi:  require('./DarkJedi'),
  ObiWan:    require('./ObiWan'),
  Paginator: require('./Paginator')
});