# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/Quixx/Models/namespace.coffee

Quixx = require '../namespace'
module.exports = Quixx.Models ||
Quixx.addNamespace 'Models', class Models extends Neptune.Base
  ;