# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/ScrollingDynamic/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScrollingDynamic', class ScrollingDynamic extends Neptune.PackageNamespace)
