# generated by Neptune Namespaces
# this file: art/react/demos/paging_scroll_element/index.coffee

module.exports =
PagingScrollElement               = require './namespace'
PagingScrollElement.ColorScroller = require './color_scroller'
PagingScrollElement.Main          = require './main'
PagingScrollElement.finishLoad(
  ["ColorScroller","Main"]
)