# generated by Neptune Namespaces v0.3.0
# file: art/react/demos/paging_scroll_element/index.coffee

(module.exports = require './namespace')
.addModules
  ColorScroller: require './color_scroller'
  Main:          require './main'