# generated by Neptune Namespaces v0.1.0
# file: art/react/demos/paging_scroll_element/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.PagingScrollElement ||
Demos.addNamespace class PagingScrollElement extends Neptune.Base
  ;