# generated by Neptune Namespaces
# file: art/react/demos/paging_scroll_element/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.PagingScrollElement ||
class Demos.PagingScrollElement extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.React.Demos.PagingScrollElement"

Demos.addNamespace Demos.PagingScrollElement