# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/MotivationalPoster/Styles/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  TheNorthernPeople: require './TheNorthernPeople'