# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/MotivationalPoster/Styles/namespace.coffee

module.exports = (require '../namespace').addNamespace('Styles', class Styles extends Neptune.PackageNamespace)
