# generated by Neptune Namespaces v0.5
# file: art/react/demos/candy_stripe/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.CandyStripe ||
Demos.addNamespace 'CandyStripe', class CandyStripe extends Neptune.Base
  ;