# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/FluxChallenge/namespace.coffee

module.exports = (require '../namespace').addNamespace('FluxChallenge', class FluxChallenge extends Neptune.PackageNamespace)
require './Components/namespace';
require './Data/namespace';
require './Models/namespace'