# generated by Neptune Namespaces
# file: art/react/demos/quixx/index.coffee

module.exports =
Quixx        = require './namespace'
Quixx.Main   = require './main'
Quixx.Models = require './models'
Quixx.finishLoad(
  ["Main"]
)