# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/quixx/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Quixx ||
Demos.addNamespace 'Quixx', class Quixx extends Neptune.Base
  ;