# generated by Neptune Namespaces
# file: art/react/demos/quixx/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Quixx ||
class Demos.Quixx extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.React.Demos.Quixx"

Demos.addNamespace Demos.Quixx