# generated by Neptune Namespaces v0.1.0
# file: art/react/demos/quixx/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Quixx ||
Demos.addNamespace class Quixx extends Neptune.Base
  ;