# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/ColorPicker/Models/namespace.coffee

ColorPicker = require '../namespace'
module.exports = ColorPicker.Models ||
ColorPicker.addNamespace 'Models', class Models extends Neptune.Base
  ;