// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/FocusAndBlur/namespace.js

module.exports = require('../namespace').addNamespace(
  'FocusAndBlur',
  class FocusAndBlur extends Neptune.PackageNamespace {}
);
