# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/FocusAndBlur/namespace.coffee

module.exports = (require '../namespace').addNamespace('FocusAndBlur', class FocusAndBlur extends Neptune.PackageNamespace)
