# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/color_picker/components/index.coffee

module.exports = require './namespace'
.addModules
  ColorPickerD: require './color_picker_1d'
  ColorPicker:  require './color_picker'   
  ColorPreview: require './color_preview'  