# generated by Neptune Namespaces v0.3.0
# file: art/react/demos/color_picker/components/index.coffee

(module.exports = require './namespace')
.addModules
  ColorPicker:   require './color_picker'
  ColorPicker1d: require './color_picker_1d'
  ColorPreview:  require './color_preview'