# generated by Neptune Namespaces
# file: art/react/demos/color_picker/components/index.coffee

module.exports =
Components               = require './namespace'
Components.ColorPicker   = require './color_picker'
Components.ColorPicker1d = require './color_picker_1d'
Components.ColorPreview  = require './color_preview'
Components.finishLoad(
  ["ColorPicker","ColorPicker1d","ColorPreview"]
)