# generated by Neptune Namespaces
# file: art/react/demos/color_picker/components/namespace.coffee

ColorPicker = require '../namespace'
module.exports = ColorPicker.Components ||
ColorPicker.addNamespace class Components extends Neptune.Base
  ;