# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/color_picker/components/namespace.coffee

ColorPicker = require '../namespace'
module.exports = ColorPicker.Components ||
ColorPicker.addNamespace 'Components', class Components extends Neptune.Base
  ;