# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ColorPicker2/Components/namespace.coffee

ColorPicker2 = require '../namespace'
module.exports = ColorPicker2.Components ||
ColorPicker2.addNamespace 'Components', class Components extends Neptune.Base
  ;
