# generated by Neptune Namespaces
# file: art/react/demos/basic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Basic ||
class Demos.Basic extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.React.Demos.Basic"

Demos.addNamespace Demos.Basic