# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/basic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Basic ||
Demos.addNamespace 'Basic', class Basic extends Neptune.Base
  ;