# generated by Neptune Namespaces
# file: art/react/demos/basic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Basic ||
Demos.addNamespace class Basic extends Neptune.Base
  ;