# generated by Neptune Namespaces v0.6
# file: art/react/demos/ScrollingInfinite/index.coffee

module.exports = require './namespace'
.addModules
  ColorScroller: require './color_scroller'
  Main:          require './main'          