# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/ScrollingInfinite/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ScrollingInfinite ||
Demos.addNamespace 'ScrollingInfinite', class ScrollingInfinite extends Neptune.Base
  ;