# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/Animations/namespace.coffee

module.exports = (require '../namespace').addNamespace('Animations', class Animations extends Neptune.PackageNamespace)
