// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Clock/index.js

(module.exports = require('./namespace'))

.addModules({
  CurrentTime: require('./CurrentTime'),
  Main:        require('./Main')
});