# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Clock/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CurrentTime: require './CurrentTime'
  Main:        require './Main'       