// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Clock/namespace.js

module.exports = require('../namespace').addNamespace(
  'Clock',
  class Clock extends Neptune.PackageNamespace {}
);
