# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Clock/namespace.coffee

module.exports = (require '../namespace').addNamespace('Clock', class Clock extends Neptune.PackageNamespace)
