# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/namespace.coffee

module.exports = (require '../namespace').addNamespace('Demos', class Demos extends Neptune.PackageNamespace)
require './Animations/namespace';
require './Basic/namespace';
require './CandyStripe/namespace';
require './CanvasPathFile/namespace';
require './Chat/namespace';
require './ChildrenMarginAnimations/namespace';
require './Clock/namespace';
require './ColorExtractor/namespace';
require './ColorPicker/namespace';
require './ColorPicker2/namespace';
require './FaceDetector/namespace';
require './FluxChallenge/namespace';
require './FocusAndBlur/namespace';
require './FocusAndNoFocus/namespace';
require './Form/namespace';
require './Gestures/namespace';
require './Layout/namespace';
require './Multitouch/namespace';
require './PhotoFilters/namespace';
require './Physics/namespace';
require './Quixx/namespace';
require './ScrollToChild/namespace';
require './ScrollingElement/namespace';
require './ScrollingInfinite/namespace';
require './Style/namespace';
require './TextInputMobileTest/namespace';
require './Textarea/namespace';
require './TicTacToe/namespace';
require './Todos/namespace';
require './VoidProps/namespace'