# generated by Neptune Namespaces
# this file: art/react/demos/buttons/index.coffee

module.exports =
Buttons      = require './namespace'
Buttons.Main = require './main'
Buttons.finishLoad(
  ["Main"]
)