# generated by Neptune Namespaces v0.3.0
# file: art/react/demos/buttons/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Buttons ||
Demos.addNamespace 'Buttons', class Buttons extends Neptune.Base
  ;