# generated by Neptune Namespaces
# file: art/react/demos/buttons/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Buttons ||
class Demos.Buttons extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.React.Demos.Buttons"

Demos.addNamespace Demos.Buttons