# generated by Neptune Namespaces
# file: art/react/demos/buttons/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Buttons ||
Demos.addNamespace class Buttons extends Neptune.Base
  ;