# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/DrumMachine/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DrumData:       require './DrumData'      
  DrumStyle:      require './DrumStyle'     
  Main:           require './Main'          
  StandardImport: require './StandardImport'
require './Components'
require './Models'