// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/DrumMachine/index.js

(module.exports = require('./namespace'))

.addModules({
  DrumData:       require('./DrumData'),
  DrumStyle:      require('./DrumStyle'),
  Main:           require('./Main'),
  StandardImport: require('./StandardImport')
});
require('./Components');
require('./Models');