// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/DrumMachine/namespace.js

module.exports = require('../namespace').addNamespace(
  'DrumMachine',
  class DrumMachine extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Models/namespace');