# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/DrumMachine/namespace.coffee

module.exports = (require '../namespace').addNamespace('DrumMachine', class DrumMachine extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'