# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/FluxChallenge/Data/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DarkJedi: require './DarkJedi'
  Worlds:   require './Worlds'  