# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/FluxChallenge/Data/namespace.coffee

FluxChallenge = require '../namespace'
module.exports = FluxChallenge.Data ||
FluxChallenge.addNamespace 'Data', class Data extends Neptune.Base
  ;
