# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Todos/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Todos:     require './Todos'    
  ViewState: require './ViewState'