# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Todos/Models/namespace.coffee

Todos = require '../namespace'
module.exports = Todos.Models ||
Todos.addNamespace 'Models', class Models extends Neptune.Base
  ;
