// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorPicker/index.js

(module.exports = require('./namespace'))

.addModules({
  Main: require('./Main')
});
require('./Components');
require('./Models');