# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ColorPicker/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main: require './Main'
require './Components'
require './Models'