// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorPicker/namespace.js

module.exports = require('../namespace').addNamespace(
  'ColorPicker',
  class ColorPicker extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Models/namespace');