# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ColorPicker/namespace.coffee

module.exports = (require '../namespace').addNamespace('ColorPicker', class ColorPicker extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'