# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Style/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Style ||
Demos.addNamespace 'Style', class Style extends Neptune.Base
  ;
