// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Todos/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  AddTodo:          require('./AddTodo'),
  ButtonLine:       require('./ButtonLine'),
  ShowTodo:         require('./ShowTodo'),
  ShowTodos:        require('./ShowTodos'),
  VisibilityButton: require('./VisibilityButton')
});