# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/DrumMachine/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DrumRow:      require './DrumRow'     
  DrumTimeslot: require './DrumTimeslot'