// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/DrumMachine/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  DrumRow:      require('./DrumRow'),
  DrumTimeslot: require('./DrumTimeslot')
});