// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/CandyStripe/namespace.js

module.exports = require('../namespace').addNamespace(
  'CandyStripe',
  class CandyStripe extends Neptune.PackageNamespace {}
);
