# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ColorPicker2/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ColorPicker2 ||
Demos.addNamespace 'ColorPicker2', class ColorPicker2 extends Neptune.Base
  ;
require './Components/namespace'