// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/TextInputMobileTest/namespace.js

module.exports = require('../namespace').addNamespace(
  'TextInputMobileTest',
  class TextInputMobileTest extends Neptune.PackageNamespace {}
);
