# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/TextInputMobileTest/namespace.coffee

module.exports = (require '../namespace').addNamespace('TextInputMobileTest', class TextInputMobileTest extends Neptune.PackageNamespace)
