# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Basic/namespace.coffee

module.exports = (require '../namespace').addNamespace('Basic', class Basic extends Neptune.PackageNamespace)
