# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Animations/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Animations ||
Demos.addNamespace 'Animations', class Animations extends Neptune.Base
  ;
