# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/MotivationalPoster/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Controls:              require './Controls'             
  CreateRandomGenerator: require './createRandomGenerator'
  Main:                  require './Main'                 
  OptionsUi:             require './OptionsUi'            
  PosterText:            require './PosterText'           
  PosterTextPreview:     require './PosterTextPreview'    
  Quotes:                require './Quotes'               
require './Data'
require './Models'
require './Styles'