# generated by Neptune Namespaces
# file: art/react/demos/quixx/models/index.coffee

module.exports =
Models       = require './namespace'
Models.Quixx = require './quixx'
Models.finishLoad(
  ["Quixx"]
)