# generated by Neptune Namespaces
# file: art/react/demos/quixx/models/namespace.coffee

Quixx = require '../namespace'
module.exports = Quixx.Models ||
Quixx.addNamespace class Models extends Neptune.Base
  ;