# generated by Neptune Namespaces v0.5
# file: art/react/demos/quixx/models/namespace.coffee

Quixx = require '../namespace'
module.exports = Quixx.Models ||
Quixx.addNamespace 'Models', class Models extends Neptune.Base
  ;