// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/FluxChallenge/namespace.js

module.exports = require('../namespace').addNamespace(
  'FluxChallenge',
  class FluxChallenge extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Data/namespace');
require('./Models/namespace');