# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/FluxChallenge/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:                require './App'               
  Button:             require './Button'            
  ListItem:           require './ListItem'          
  YodasCurrentPlanet: require './YodasCurrentPlanet'