// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/FluxChallenge/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  App:                require('./App'),
  Button:             require('./Button'),
  ListItem:           require('./ListItem'),
  YodasCurrentPlanet: require('./YodasCurrentPlanet')
});