# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ColorExtractor/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ColorExtractor ||
Demos.addNamespace 'ColorExtractor', class ColorExtractor extends Neptune.Base
  ;
