# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/FluxChallenge/Models/namespace.coffee

FluxChallenge = require '../namespace'
module.exports = FluxChallenge.Models ||
FluxChallenge.addNamespace 'Models', class Models extends Neptune.Base
  ;
