# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/CandyStripe/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.CandyStripe ||
Demos.addNamespace 'CandyStripe', class CandyStripe extends Neptune.Base
  ;