# generated by Neptune Namespaces v3.x.x
# file: Art/Suite/Demos/Quixx/namespace.coffee

module.exports = (require '../namespace').addNamespace('Quixx', class Quixx extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'