# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Quixx/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Quixx ||
Demos.addNamespace 'Quixx', class Quixx extends Neptune.Base
  ;
require './Components/namespace';
require './Models/namespace'