# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/PhotoFilters/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BrightnessAndContrast: require './BrightnessAndContrast'
  ColorMatrix:           require './ColorMatrix'          
  Filters:               require './Filters'              
  Main:                  require './Main'                 