// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/PhotoFilters/index.js

(module.exports = require('./namespace'))

.addModules({
  BrightnessAndContrast: require('./BrightnessAndContrast'),
  ColorMatrix:           require('./ColorMatrix'),
  Filters:               require('./Filters'),
  Main:                  require('./Main')
});