# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/PhotoFilters/namespace.coffee

module.exports = (require '../namespace').addNamespace('PhotoFilters', class PhotoFilters extends Neptune.PackageNamespace)
