// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/PhotoFilters/namespace.js

module.exports = require('../namespace').addNamespace(
  'PhotoFilters',
  class PhotoFilters extends Neptune.PackageNamespace {}
);
