# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/VoidProps/namespace.coffee

module.exports = (require '../namespace').addNamespace('VoidProps', class VoidProps extends Neptune.PackageNamespace)
