# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/physics/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Physics ||
Demos.addNamespace 'Physics', class Physics extends Neptune.Base
  ;