# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/ColorPicker/Components/index.coffee

module.exports = require './namespace'
.addModules
  ColorPicker:   require './ColorPicker'  
  ColorPicker1D: require './ColorPicker1D'
  ColorPreview:  require './ColorPreview' 