# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ColorPicker/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ColorPicker:   require './ColorPicker'  
  ColorPicker1D: require './ColorPicker1D'
  ColorPreview:  require './ColorPreview' 