# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/ColorPicker/Components/namespace.coffee

ColorPicker = require '../namespace'
module.exports = ColorPicker.Components ||
ColorPicker.addNamespace 'Components', class Components extends Neptune.Base
  ;