// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollingInfinite/index.js

(module.exports = require('./namespace'))

.addModules({
  ColorScroller: require('./ColorScroller'),
  Main:          require('./Main')
});