// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollingInfinite/namespace.js

module.exports = require('../namespace').addNamespace(
  'ScrollingInfinite',
  class ScrollingInfinite extends Neptune.PackageNamespace {}
);
