# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Loader: require './Loader'
  Main:   require './Main'  
require './Demos'