# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/namespace.coffee

Art = require '../namespace'
module.exports = Art.Suite ||
Art.addNamespace 'Suite', class Suite extends Neptune.Base
  ;
require './Demos/namespace'