// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollToChild/namespace.js

module.exports = require('../namespace').addNamespace(
  'ScrollToChild',
  class ScrollToChild extends Neptune.PackageNamespace {}
);
