# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ScrollToChild/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScrollToChild', class ScrollToChild extends Neptune.PackageNamespace)
