# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/Todos/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Todos ||
Demos.addNamespace 'Todos', class Todos extends Neptune.Base
  ;
require './Components/namespace';
require './Models/namespace'