// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorPicker/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  CurrentColor: require('./CurrentColor')
});