# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ChildrenMarginAnimations/namespace.coffee

module.exports = (require '../namespace').addNamespace('ChildrenMarginAnimations', class ChildrenMarginAnimations extends Neptune.PackageNamespace)
