// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ChildrenMarginAnimations/namespace.js

module.exports = require('../namespace').addNamespace(
  'ChildrenMarginAnimations',
  class ChildrenMarginAnimations extends Neptune.PackageNamespace {}
);
