// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Todos/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  Todos:     require('./Todos'),
  ViewState: require('./ViewState')
});