# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Todos/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Todos:     require './Todos'    
  ViewState: require './ViewState'