# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Todos/Models/namespace.coffee

module.exports = (require '../namespace').addNamespace('Models', class Models extends Neptune.PackageNamespace)
