# generated by Neptune Namespaces
# file: art/react/demos/hot_basic/index.coffee

module.exports =
HotBasic      = require './namespace'
HotBasic.Main = require './main'
HotBasic.finishLoad(
  ["Main"]
)