# generated by Neptune Namespaces v1.x.x
# file: art/react/demos/hot_basic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.HotBasic ||
Demos.addNamespace 'HotBasic', class HotBasic extends Neptune.Base
  ;