# generated by Neptune Namespaces
# file: ../../../art/react/demos/hot_basic/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.HotBasic ||
class Demos.HotBasic extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.React.Demos.HotBasic"

Demos.addNamespace Demos.HotBasic