// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/FaceDetector/namespace.js

module.exports = require('../namespace').addNamespace(
  'FaceDetector',
  class FaceDetector extends Neptune.PackageNamespace {}
);
