# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/FaceDetector/namespace.coffee

module.exports = (require '../namespace').addNamespace('FaceDetector', class FaceDetector extends Neptune.PackageNamespace)
