# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/Demos/ColorPicker/index.coffee

module.exports = require './namespace'
.addModules
  Main: require './Main'
require './Components'
require './Models'