# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/Demos/ColorPicker/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.ColorPicker ||
Demos.addNamespace 'ColorPicker', class ColorPicker extends Neptune.Base
  ;
require './Components/namespace';
require './Models/namespace'