// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Quixx/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  ColorCheckBox: require('./ColorCheckBox'),
  ColorRow:      require('./ColorRow'),
  ColorScore:    require('./ColorScore'),
  Logo:          require('./Logo'),
  Quixx:         require('./Quixx')
});