# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Quixx/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ColorCheckBox: require './ColorCheckBox'
  ColorRow:      require './ColorRow'     
  ColorScore:    require './ColorScore'   
  Logo:          require './Logo'         
  Quixx:         require './Quixx'        