# generated by Neptune Namespaces v3.x.x
# file: Art.Suite.Demos/Demos/ScrollingInfinite/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ColorScroller: require './ColorScroller'
  Main:          require './Main'         