# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ScrollingElement/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Button:         require './Button'        
  LineItem:       require './LineItem'      
  SimpleLineItem: require './SimpleLineItem'