// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollingElement/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  Button:         require('./Button'),
  LineItem:       require('./LineItem'),
  SimpleLineItem: require('./SimpleLineItem')
});