// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollingElement/Widgets/namespace.js

module.exports = require('../namespace').addNamespace(
  'Widgets',
  class Widgets extends Neptune.PackageNamespace {}
);
