// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollingElement/index.js

(module.exports = require('./namespace'))

.addModules({
  DynamicScroller:   require('./DynamicScroller'),
  Main:              require('./Main'),
  ScrollElementDemo: require('./ScrollElementDemo')
});
require('./Widgets');