# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ScrollingElement/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DynamicScroller:   require './DynamicScroller'  
  Main:              require './Main'             
  ScrollElementDemo: require './ScrollElementDemo'
require './Widgets'