# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ScrollingElement/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Button:          require './Button'         
  DynamicScroller: require './DynamicScroller'
  Main:            require './Main'           