# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ScrollingElement/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScrollingElement', class ScrollingElement extends Neptune.PackageNamespace)
