// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ScrollingElement/namespace.js

module.exports = require('../namespace').addNamespace(
  'ScrollingElement',
  class ScrollingElement extends Neptune.PackageNamespace {}
);
require('./Widgets/namespace');