// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/ColorExtractor/namespace.js

module.exports = require('../namespace').addNamespace(
  'ColorExtractor',
  class ColorExtractor extends Neptune.PackageNamespace {}
);
