# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/ColorExtractor/namespace.coffee

module.exports = (require '../namespace').addNamespace('ColorExtractor', class ColorExtractor extends Neptune.PackageNamespace)
