# generated by Neptune Namespaces v3.x.x
# file: Art.SuiteDemos/Demos/Form/namespace.coffee

module.exports = (require '../namespace').addNamespace('Form', class Form extends Neptune.PackageNamespace)
