// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/Form/namespace.js

module.exports = require('../namespace').addNamespace(
  'Form',
  class Form extends Neptune.PackageNamespace {}
);
